[package]
name = "frizbee"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.5"
nucleo-matcher = "0.3.1"

[[bench]]
name = "lib"
harness = false

[dependencies]
memchr = "2.7.4"
