[package]
name = "frizbee"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.5"
iai-callgrind = "0.14.0"
nucleo-matcher = "0.3.1"
rand = "0.9.0"
rand_distr = "0.5.1"

[[bench]]
name = "lib"
harness = false

[[bench]]
name = "smith_waterman_iai"
harness = false
